server:
  port: 8081
spring:
  mail:
    host: smtp.qq.com
    username: *******@qq.com
    password: *******
    
  datasource:
    password: 9999
    username: root
    url: jdbc:mysql://127.0.0.1:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: 9999
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 100ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

  mapper-locations: classpath:/Mapper/*.xml
